### ISSUE TITLE
Why do you use these  onnx files?

### ISSUE THREAD

**Issue by winktool** [Hyuto/yolov5-seg-onnxruntime-web#1]
https://github.com/Hyuto/yolov5-seg-onnxruntime-web/blob/master/src/App.js#L31
and do you have nodejs version?
may be you can use these dependencies:
```"jimp": "^0.16.2"```
```"canvas": "^2.10.2"```

**Comment by Hyuto** [comment]
Hello, those additional onnx file is required to make object segmentation happen in browser. 

* The nms file is for perform Non Max Suppression. Since `opencv.js` doesn't inculde `NMS` operator, I use onnx `nms` operator so we can perform high performance NMS on browser.
* The mask file is to perform post processing mask from the `YOLOv5` model. `YOLOv5-seg` doesn't give an end2end model we must figure it out how to process the mask. Since `opencv.js` not powerful as we can use on C++ or Python and there is no `numpy` in `javascript`, the only way to do is to use onnx operators to process tersor/matrix.

Sorry I'll not do the node version, but I guess there is not much difference with this. You only have to figure it out how to serve those onnx models in node just like [yolov7-node](https://github.com/Hyuto/yolov7-node) and I don't think those library will help.

**Comment by winktool** [comment]
The project examples that are currently searchable are based on python and c++ implementations. Maybe I can pay you to implement a version of the code based on the nodejs implementation. No additional onnx files are required.

**Comment by winktool** [comment]
> Hello, those additional onnx file is required to make object segmentation happen in browser.
> 
> * The nms file is for perform Non Max Suppression. Since `opencv.js` doesn't inculde `NMS` operator, I use onnx `nms` operator so we can perform high performance NMS on browser.
> * The mask file is to perform post processing mask from the `YOLOv5` model. `YOLOv5-seg` doesn't give an end2end model we must figure it out how to process the mask. Since `opencv.js` not powerful as we can use on C++ or Python and there is no `numpy` in `javascript`, the only way to do is to use onnx operators to process tersor/matrix.
> 
> Sorry I'll not do the node version, but I guess there is not much difference with this. You only have to figure it out how to serve those onnx models in node just like [yolov7-node](https://github.com/Hyuto/yolov7-node) and I don't think those library will help.

Can you explain how to generate these onnx files?

**Comment by Hyuto** [comment]
> The project examples that are currently searchable are based on python and c++ implementations. Maybe I can pay you to implement a version of the code based on the nodejs implementation. No additional onnx files are required.

I think with current opencv.js and onnxruntime-node can't perform such complex matrix operation, so it's impossible to operate wiithout those onnx files.

**Comment by Hyuto** [comment]
> Could you explain how to generate these onnx files?

I use [onnx-graphsurgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/docs/index.html) to generate those onnx files. you can take a look at this script [mask.py](https://github.com/Hyuto/fun/blob/master/test-onnx-graph-surgeon/mask.py)
